name: carbgem
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.18+17

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  flutter_inapp_purchase: "^5.0.0"
  flutter_launcher_icons: "^0.9.1"
  cupertino_icons: ^1.0.2
  device_info_plus: ^2.0.1
  package_info_plus: ^1.0.4
  flutter_svg: ^0.22.0
  awesome_dialog: ^2.1.1
  im_stepper: 0.1.2+10
  # for implementing firebase login using flutter bloc concept
  firebase_core: 1.12.0
  firebase_storage: "^10.0.1"
  bloc: ^7.0.0
  device_info: ^2.0.2
  equatable:  ^2.0.0
  flow_builder: 0.0.3
  flutter_bloc: ^7.0.0
  font_awesome_flutter: ^9.0.0
  formz: ^0.4.0
  meta: ^1.3.0
  very_good_analysis: ^2.1.0
  http: ^0.13.3
  flutter_map: ^0.14.0
  latlng: ^0.1.0
  image_picker: ^0.8.5
  photo_view: ^0.12.0
  fl_chart: ^0.36.3
  flutter_secure_storage: ^4.2.1
  before_after: ^2.1.0
  flutter_typeahead: ^3.2.0
  ripple_animation: ^0.0.1+2
  rounded_loading_button: ^2.0.6
  loading_animations: ^2.2.0
  geodesy: ^0.4.0-nullsafety.0
  in_app_purchase: 3.0.8
  firebase_analytics: ^8.3.2
  convex_bottom_bar: 3.0.0
  curved_drawer_fork: ^0.0.1
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  provider: ^6.0.1
  shared_preferences: ^2.0.0
  new_version: ^0.2.3
  multi_select_flutter: ^4.0.0
  modal_bottom_sheet: ^2.0.0
  circular_menu: ^1.2.3
  tflite_flutter: ^0.9.0
  logger: ^1.0.0
  tflite_flutter_helper: ^0.3.0
#  data for flutter 2.5.0
  camera: ^0.9.6
  cache:
    path: packages/cache
  authentication_repository:
    path: packages/authentication_repository
  form_inputs:
    path: packages/form_inputs
  bitte_api:
    path: packages/bitte_api

dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  flutter_flavorizr: ^2.0.0
  flutter_flavor: ^3.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/model_tflite/

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/carbgem_logo.png"
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios:

  flavors:
    development:
      app:
        name: "Development"

      android:
        applicationId: "com.carbgem.bitte.dev"
        firebase:
          config: ".firebase/dev/google-services.json"

      ios:
        bundleId: "com.carbgem.bitte.dev"
        firebase:
          config: ".firebase/dev/GoogleService-info.plist"

    staging:
      app:
        name: "Staging"

      android:
        applicationId: "com.carbgem.bitte.stg"
        firebase:
          config: ".firebase/stg/google-services.json"
      ios:
        bundleId: "com.carbgem.bitte.stg"
        firebase:
          config: ".firebase/stg/GoogleService-info.plist"

    production:
      app:
        name: "BiTTE"

      android:
        applicationId: "com.carbgem.bitte"
        firebase:
          config: ".firebase/prod/google-services.json"

      ios:
        bundleId: "com.carbgem.bitte.dev"
        firebase:
          config: ".firebase/prod/GoogleService-info.plist"