name: bitte_api
description: A Dart API Client for the Bitte Backend API.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  meta: ^1.3.0
  equatable: ^2.0.0
  latlong2: ^0.8.0
  flutter_map: ^0.14.0
  cache:
    path: ../cache

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  flutter_flavorizr: ^2.0.0
  flutter_flavor: ^3.0.3